import StyleDictionary from 'style-dictionary';

/**
 * Tailwind v4 `@theme` 블록을 생성하는 커스텀 포맷.
 *
 * 토큰 path를 kebab-case로 평탄화하고, 카테고리별 Tailwind 변수 prefix를 매핑합니다.
 * - color/* → --color-*
 * - dimension(radius) → --radius-*
 * - dimension(spacing) → --spacing-*
 * - dimension(fontSize) → --text-*
 * - fontWeight → --font-weight-*
 * - fontFamily → --font-*
 */
StyleDictionary.registerFormat({
  name: 'tailwind/theme',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      .map((token) => {
        const cssVar = buildCssVarName(token);
        if (!cssVar) return null;
        return `  ${cssVar}: ${token.$value ?? token.value};`;
      })
      .filter(Boolean);

    return [
      '/* This file is auto-generated by Style Dictionary. Do not edit directly. */',
      '/* Run `pnpm tokens:build` to regenerate. */',
      '',
      '@theme {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
});

/**
 * 토큰 path를 Tailwind v4 CSS variable 이름으로 변환합니다.
 *
 * 토큰 path 예시:
 * - Colors.Brand.Scale.500 → --color-brand-500
 * - Colors.Brand.Alpha.10 → --color-brand-alpha-10
 * - color.surface.success → --color-surface-success
 * - Radius.8 → --radius-8
 * - Spacing.16 → --spacing-16
 * - Typography.size.16 → --text-16
 * - Typography.fontWeight.medium → --font-weight-medium
 * - Typography.fontFamily.brand → --font-brand
 */
function buildCssVarName(token) {
  const path = token.path.map((segment) => segment.toLowerCase());

  // Semantic 색상: color.surface.success → --color-surface-success
  if (path[0] === 'color') {
    return `--${path.join('-')}`;
  }

  // Core 색상: colors.brand.scale.500 → --color-brand-500
  //          colors.brand.alpha.10 → --color-brand-alpha-10
  //          colors.white.default → --color-white
  //          colors.white.alpha.30 → --color-white-alpha-30
  if (path[0] === 'colors') {
    const rest = path.slice(1).filter((seg) => seg !== 'scale' && seg !== 'default');
    return `--color-${rest.join('-')}`;
  }

  // Radius / Spacing: radius.8 → --radius-8, spacing.16 → --spacing-16
  if (path[0] === 'radius' || path[0] === 'spacing') {
    return `--${path.join('-')}`;
  }

  // Typography
  if (path[0] === 'typography') {
    const [, category, name] = path;
    if (category === 'size') return `--text-${name}`;
    if (category === 'fontweight') return `--font-weight-${name}`;
    if (category === 'fontfamily') return `--font-${name}`;
  }

  return null;
}

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'apps/client/src/styles/',
      files: [
        {
          destination: 'tokens.generated.css',
          format: 'tailwind/theme',
        },
      ],
    },
  },
  log: {
    verbosity: 'verbose',
  },
};
